name: BUILD - AAB
on:
  workflow_dispatch:
jobs:
  react_native:
    name: build aab
    uses: GabrielSoares-Dev/workflows/.github/workflows/react-native-build-aab.yml@master
    with:
      node_version: '22.x'
      java_version: '17'
      env_content: |
        API_URL=https://api.life-control.com.br
