name: BUILD - APK
on:
  workflow_dispatch:
jobs:
  react_native:
    name: build apk
    uses: GabrielSoares-Dev/workflows/.github/workflows/react-native-build-apk.yml@master
    with:
      node_version: '22.x'
      java_version: '17'
      env_content: |
        API_URL=https://api.life-control.com.br
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}