name: BUILD - APK
on:
  workflow_dispatch:
jobs:
  react_native:
    name: build apk
    uses: GabrielSoares-Dev/workflows/.github/workflows/react-native-build-apk.yml@master
    with:
      node_version: '22.x'
      java_version: '17'