name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  react_native:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/react-native-CI.yml@master
    with:
      node_version: '22.x'